#!/usr/bin/env sh

# shellcheck shell=sh

# SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
# SPDX-License-Identifier: Apache-2.0

set -eu

if [ -z "${GIT_REFLOG_ACTION+x}" ]; then
  git stash --quiet --include-untracked --keep-index

  trap 'git stash pop --quiet 2>/dev/null' EXIT INT QUIT TSTP
fi

shfmt --diff --indent 2 --case-indent --binary-next-line --simplify .
find zfunc -type f -print0 | xargs -0L1 shfmt --diff --indent 2 --case-indent --binary-next-line --simplify

find . -type f -name '*.sh' -print0 | xargs -0L1 shellcheck
find zfunc -type f -print0 | xargs -0L1 shellcheck

yamllint --strict .

# https://github.com/hadolint/hadolint#cli
hadolint --no-color scripts/docker/Dockerfile
