#!/usr/bin/env sh

# shellcheck shell=sh

# SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
# SPDX-License-Identifier: Apache-2.0

set -eu

git_root="$(git rev-parse --show-toplevel)"
cd "${git_root}" || exit 1
unset git_root

shfmt --diff --indent 2 --case-indent --binary-next-line --simplify .
find zfunc -type f -print0 | xargs -0 shfmt --diff --indent 2 --case-indent --binary-next-line --simplify

find . -type f -name '*.sh' -print0 | xargs -0 shellcheck
find zfunc -type f -print0 | xargs -0 shellcheck

yamllint --strict .

# https://github.com/hadolint/hadolint#cli
hadolint --no-color scripts/docker/Dockerfile
