#!/usr/bin/env sh

# shellcheck shell=sh

# SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
# SPDX-License-Identifier: Apache-2.0

# hadolint needs to be in $PATH
# https://github.com/hadolint/hadolint
#   Mac:
#     brew install hadolint
#   Linux:
#     sudo apt-get install hadolint

# _shellcheck needs to be in $PATH
# https://www.shellcheck.net
#   Mac:
#     brew install shellcheck
#   Linux:
#     sudo apt-get install shellcheck

# shfmt needs to be in $PATH
# https://github.com/mvdan/sh
#   Mac:
#     brew install shfmt
#   Linux:
#     sudo apt-get install shfmt

# yamllint needs to be in $PATH
# https://yamllint.readthedocs.io/en/stable/
#   Mac:
#     brew install yamllint
#   Linux:
#     sudo apt-get install yamllint

set -eu

if [ -z "${GIT_REFLOG_ACTION+x}" ]; then
  git stash --quiet --include-untracked --keep-index

  trap 'git stash pop --quiet 2>/dev/null' EXIT INT QUIT TSTP
fi

cd "$(git rev-parse --show-toplevel)" || exit 1

set +e

diff="$(find .githooks zfunc -type f -print0 | xargs -0L1 shfmt --diff --indent 2 --case-indent --binary-next-line --simplify)"
if [ -n "${diff}" ]; then
  printf '%s\n' "${diff}" >&2
  exit 1
fi
diff="$(shfmt --diff --indent 2 --case-indent --binary-next-line --simplify .)"
if [ -n "${diff}" ]; then
  printf '%s\n' "${diff}" >&2
  exit 1
fi
unset diff

set -e

{ find scripts -type f -name '*.sh' -exec shellcheck {} \;; } >&2

{ find .githooks zfunc -type f -exec shellcheck {} \;; } >&2

yamllint --strict . >&2

# https://github.com/hadolint/hadolint#cli
hadolint scripts/docker/Dockerfile >&2
