---
# SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
# SPDX-License-Identifier: Apache-2.0

# https://github.com/hadolint/hadolint#configure

failure-threshold: style
trustedRegistries:
  - docker.io
