// SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
// SPDX-License-Identifier: Apache-2.0
= sdavids-shell-misc
Sebastian Davids <sdavids@gmx.de>
// Metadata:
:description: Miscellaneous shell-related scripts and functions.
// Settings:
:sectnums:
:sectanchors:
:sectlinks:
:toc: macro
:toclevels: 3
:toc-placement!:
:source-highlighter: rouge
:rouge-style: github
:docinfo: shared
:docinfodir: docs/asciidoc/docinfo
// Refs:
:uri-contributor-covenant: https://www.contributor-covenant.org
:uri-apache-license: https://www.apache.org/licenses/LICENSE-2.0
:uri-google-style: https://github.com/google/gts

ifdef::env-browser[:outfilesuffix: .adoc]

ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:tip-caption: :bulb:
:warning-caption: :warning:
:badges:
endif::[]

ifdef::badges[]
image:https://img.shields.io/github/license/sdavids/sdavids-shell-misc[Apache License,Version 2.0,link={uri-apache-license}]
image:https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg[Contributor Covenant,Version 2.1,link={uri-contributor-covenant}]
image:https://img.shields.io/badge/code%20style-google-blueviolet.svg[Code Style: Google,link={uri-google-style}]
image:https://img.shields.io/osslifecycle/sdavids/sdavids-shell-misc[OSS Lifecycle]
image:https://img.shields.io/maintenance/yes/2024[Maintenance]
image:https://img.shields.io/github/last-commit/sdavids/sdavids-shell-misc[GitHub last commit]
image:http://isitmaintained.com/badge/resolution/sdavids/sdavids-shell-misc.svg[Resolution Time]
image:http://isitmaintained.com/badge/open/sdavids/sdavids-shell-misc.svg[Open Issues]
endif::[]

toc::[]

{description}

== Scripts

== Functions

The functions need to be copied into an https://docstore.mik.ua/orelly/unix3/upt/ch29_13.htm#upt3-CHP-29-SECT-13.2.2[$FPATH directory].

[IMPORTANT]
====
The filename needs to match the name of the function.
====

[TIP]
====
Example zsh setup:

[source,shell]
----
$ mkdir ~/.zfunc
----

.~/.zshrc
[source,shell]
----
readonly ext_func="${HOME}/.zfunc"

export FPATH="${ext_func}:${FPATH}"

for f in ${ext_func}; do
  # shellcheck disable=SC2046
  autoload -Uz $(ls "${f}")
done
----

The functions should be copied into `~/.zfunc`.
====

== License

Apache License, Version 2.0 (link:LICENSES/Apache-2.0.txt[Apache-2.0.txt] or {uri-apache-license}).

== Contribution

See link:CONTRIBUTING{outfilesuffix}[].

== Code of Conduct

We abide by the {uri-contributor-covenant}[Contributor Covenant, Version 2.1] and ask that you do as well.

For more information, please see link:CODE_OF_CONDUCT{outfilesuffix}[].

== Development Environment Setup

[IMPORTANT]
====
After initializing the repository you need to install the Git hooks via:

[source,shell]
----
$ git config core.hooksPath .githooks
----
====

=== Installation

[#shellcheck]
==== shellcheck

===== Linux

[source,shell]
----
$ sudo apt-get install shellcheck
----

===== Mac

[source,shell]
----
$ brew install shellcheck
----

[#yamllint]
==== yamllint

===== Linux

[source,shell]
----
$ sudo apt-get install yamllint
----

===== Mac

[source,shell]
----
$ brew install yamllint
----
