// SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
// SPDX-License-Identifier: Apache-2.0
= sdavids-shell-misc
Sebastian Davids <sdavids@gmx.de>
// Metadata:
:description: Miscellaneous shell-related scripts and functions.
// Settings:
:sectnums:
:sectanchors:
:sectlinks:
:toc: macro
:toclevels: 3
:toc-placement!:
:source-highlighter: rouge
:rouge-style: github
:docinfo: shared
:docinfodir: docs/asciidoc/docinfo
// Refs:
:uri-contributor-covenant: https://www.contributor-covenant.org
:uri-apache-license: https://www.apache.org/licenses/LICENSE-2.0
:uri-google-style: https://github.com/google/gts

ifdef::env-browser[:outfilesuffix: .adoc]

ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:tip-caption: :bulb:
:warning-caption: :warning:
:badges:
endif::[]

ifdef::badges[]
image:https://img.shields.io/github/license/sdavids/sdavids-shell-misc[Apache License,Version 2.0,link={uri-apache-license}]
image:https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg[Contributor Covenant,Version 2.1,link={uri-contributor-covenant}]
image:https://img.shields.io/badge/code%20style-google-blueviolet.svg[Code Style: Google,link={uri-google-style}]
image:https://img.shields.io/osslifecycle/sdavids/sdavids-shell-misc[OSS Lifecycle]
image:https://img.shields.io/maintenance/yes/2024[Maintenance]
image:https://img.shields.io/github/last-commit/sdavids/sdavids-shell-misc[GitHub last commit]
image:http://isitmaintained.com/badge/resolution/sdavids/sdavids-shell-misc.svg[Resolution Time]
image:http://isitmaintained.com/badge/open/sdavids/sdavids-shell-misc.svg[Open Issues]
endif::[]

toc::[]

{description}

== Scripts

[#general-scripts]
=== General

This section contains generally useful scripts:

<<create-timestamp-file,create-timestamp-file>>:: create a file with a timestamp
<<loop,loop>>:: repeat a script repeatedly
<<hash-filename,hash-filename>>:: insert a hash into a filename
<<shellscript-check,shellscript-check>>:: shellcheck `*.sh` files in the given directory

[#create-timestamp-file]
==== create-timestamp-file

link:scripts/general/create-timestamp-file.sh[This script] will create a file with the given name; the content will be the https://www.rfc-editor.org/rfc/rfc3339[RFC 3339 timestamp] of the file's creation, e.g.:

[source]
----
2024-01-16T16:33:12Z
----

===== Usage

[source,shell]
----
$ scripts/general/create-timestamp-file.sh .timestamp
$ cat .timestamp
2024-02-19T10:37:02Z
----

[#hash-filename]
==== hash-filename

link:scripts/general/hash-filename.sh[This script] will rename a given file; the new filename will have a hash inserted, e.g.:

`test.txt` ⇒ `test.da39a3e.txt`

Use the optional second parameter `-e` to print the new filename to stdout.

===== Usage

[source,shell]
----
$ scripts/general/hash-filename.sh test.txt
$ scripts/general/hash-filename.sh test-echo.txt -e
test-echo.da39a3e.txt
$ find . \( -type f -name '*.jpg' -o -name '*.png' \) -exec scripts/general/hash-filename.sh {} ';'
----

[#loop]
==== loop

link:scripts/general/loop.sh[This script] will invoke the given script repeatedly with a given delay between invocations and an initial delay.

The loop will finish when the given script has an exit code other than `100`.

===== Usage

.with-exit-condition.sh
[source,shell]
----
#!/usr/bin/env sh
if [ ... ]; then
  exit 0 # finish loop
fi
----

.infinite.sh
[source,shell]
----
#!/usr/bin/env sh
exit 100 # infinite loop
----

[source,shell]
----
$ scripts/general/loop.sh 10 10 some-script.sh
$ scripts/general/loop.sh 5 0 some-otherscript-with-parameters.sh a 1
----

[#shellscript-check]
==== shellscript-check

link:scripts/general/shellscript-check.sh[This script] will invoke https://www.shellcheck.net[shellcheck] on `*.sh` files in the given directory (`$PWD` if not given) and its subdirectories.

[NOTE]
====
`shellcheck` needs to be <<shellcheck,installed>>.
====

[TIP]
====
If you copy this script into a Node.js-based project you should exclude the `node_modules` directory:

`find … -name '*.sh' -not -path '*/node_modules/*' -print0 …`
====

===== Usage

[source,shell]
----
$ scripts/general/shellscript-check.sh
$ scripts/general/shellscript-check.sh /tmp
----

== Functions

The functions need to be copied into an https://docstore.mik.ua/orelly/unix3/upt/ch29_13.htm#upt3-CHP-29-SECT-13.2.2[$FPATH directory].

[IMPORTANT]
====
The filename needs to match the name of the function.
====

[TIP]
====
Example zsh setup:

[source,shell]
----
$ mkdir ~/.zfunc
----

.~/.zshrc
[source,shell]
----
readonly ext_func="${HOME}/.zfunc"

export FPATH="${ext_func}:${FPATH}"

for f in ${ext_func}; do
  # shellcheck disable=SC2046
  autoload -Uz $(ls "${f}")
done
----

The functions should be copied into `~/.zfunc`.
====

== License

Apache License, Version 2.0 (link:LICENSES/Apache-2.0.txt[Apache-2.0.txt] or {uri-apache-license}).

== Contribution

See link:CONTRIBUTING{outfilesuffix}[].

== Code of Conduct

We abide by the {uri-contributor-covenant}[Contributor Covenant, Version 2.1] and ask that you do as well.

For more information, please see link:CODE_OF_CONDUCT{outfilesuffix}[].

== Development Environment Setup

[IMPORTANT]
====
After initializing the repository you need to install the Git hooks via:

[source,shell]
----
$ git config core.hooksPath .githooks
----
====

=== Installation

[#shellcheck]
==== shellcheck

===== Linux

[source,shell]
----
$ sudo apt-get install shellcheck
----

===== Mac

[source,shell]
----
$ brew install shellcheck
----

[#yamllint]
==== yamllint

===== Linux

[source,shell]
----
$ sudo apt-get install yamllint
----

===== Mac

[source,shell]
----
$ brew install yamllint
----
