// SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
// SPDX-License-Identifier: Apache-2.0
= sdavids-shell-misc
Sebastian Davids <sdavids@gmx.de>
// Metadata:
:description: Miscellaneous shell-related scripts and functions.
// Settings:
:sectnums:
:sectanchors:
:sectlinks:
:toc: macro
:toclevels: 3
:toc-placement!:
:source-highlighter: rouge
:rouge-style: github
:docinfo: shared
:docinfodir: docs/asciidoc/docinfo
// Refs:
:uri-contributor-covenant: https://www.contributor-covenant.org
:uri-apache-license: https://www.apache.org/licenses/LICENSE-2.0
:uri-google-style: https://github.com/google/gts

ifdef::env-browser[:outfilesuffix: .adoc]

ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:tip-caption: :bulb:
:warning-caption: :warning:
:badges:
endif::[]

ifdef::badges[]
image:https://img.shields.io/github/license/sdavids/sdavids-shell-misc[Apache License,Version 2.0,link={uri-apache-license}]
image:https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg[Contributor Covenant,Version 2.1,link={uri-contributor-covenant}]
image:https://img.shields.io/badge/code%20style-google-blueviolet.svg[Code Style: Google,link={uri-google-style}]
image:https://img.shields.io/osslifecycle/sdavids/sdavids-shell-misc[OSS Lifecycle]
image:https://img.shields.io/maintenance/yes/2024[Maintenance]
image:https://img.shields.io/github/last-commit/sdavids/sdavids-shell-misc[GitHub last commit]
image:http://isitmaintained.com/badge/resolution/sdavids/sdavids-shell-misc.svg[Resolution Time]
image:http://isitmaintained.com/badge/open/sdavids/sdavids-shell-misc.svg[Open Issues]
endif::[]

toc::[]

{description}

== Scripts

[#general-scripts]
=== General

This section contains generally useful scripts:

<<counter,counter>>:: create a counter
<<create-timestamp-file,create-timestamp-file>>:: create a file with a timestamp
<<loop,loop>>:: repeat a script repeatedly
<<hash-filename,hash-filename>>:: insert a hash into a filename
<<shellscript-check,shellscript-check>>:: shellcheck `*.sh` files in the given directory

[#counter]
==== counter

link:scripts/general/counter.sh[This script] will create a counter with the given name.

The optional second positive integer parameter will stop the counter when the current count is equal or larger than the given argument.

Invoking this script will print the current count to stdout unless the counter has been removed.

The exit code of the script will be `100` when the count has been increased or `0` when the counter has been removed.

The count is persisted in a file in a temporary directory or `COUNTER_DIR` if set in the environment.

===== Usage

.toggle.sh
[source,shell]
----
#!/usr/bin/env sh
scripts/general/counter.sh toggle 1 1>/dev/null
if [ $? -eq 100 ]; then
  echo 'on'
else
  echo 'off'
fi
----

.retry.sh
[source,shell]
----
#!/usr/bin/env sh
COUNTER_DIR="${XDG_STATE_HOME:=${HOME}}/retry" scripts/general/counter.sh retry 3 1>/dev/null
if [ $? -ne 100 ]; then
  echo 'tried enough times' >&2
  exit 50
fi
----

[source,shell]
----
$ scripts/general/counter.sh my-counter 2
1
$ echo $?
100
$ scripts/general/counter.sh my-counter 2
2
$ echo $?
100
$ scripts/general/counter.sh my-counter 2
$ echo $?
0
$ ./toggle.sh
on
$ ./toggle.sh
off
$ ./toggle.sh
on
$ mkdir -p "${XDG_STATE_HOME:=${HOME}}/retry"
$ ./retry.sh
$ ls "${XDG_STATE_HOME:=${HOME}}/retry"
counter-retry
$ cat /home/example/.local/state/retry/counter-retry
1
$ ./retry.sh
$ cat /home/example/.local/state/retry/counter-retry
2
$ ./retry.sh
$ cat /home/example/.local/state/retry/counter-retry
3
$ ./retry.sh
tried enough times
$ ls "${XDG_STATE_HOME:=${HOME}}/retry"
$ rm -rf "${XDG_STATE_HOME:=${HOME}}/retry"
----

===== Related Scripts

. <<loop,loop>>
+
[source,shell]
----
$ scripts/general/loop.sh 1 0 scripts/general/counter.sh my-counter 5
12345
----

[#create-timestamp-file]
==== create-timestamp-file

link:scripts/general/create-timestamp-file.sh[This script] will create a file with the given name; the content will be the https://www.rfc-editor.org/rfc/rfc3339[RFC 3339 timestamp] of the file's creation, e.g.:

[source]
----
2024-01-16T16:33:12Z
----

===== Usage

[source,shell]
----
$ scripts/general/create-timestamp-file.sh .timestamp
$ cat .timestamp
2024-02-19T10:37:02Z
----

[#hash-filename]
==== hash-filename

link:scripts/general/hash-filename.sh[This script] will rename a given file; the new filename will have a hash inserted, e.g.:

`test.txt` ⇒ `test.da39a3e.txt`

Use the optional second parameter `-e` to print the new filename to stdout.

===== Usage

[source,shell]
----
$ scripts/general/hash-filename.sh test.txt
$ scripts/general/hash-filename.sh test-echo.txt -e
test-echo.da39a3e.txt
$ find . \( -type f -name '*.jpg' -o -name '*.png' \) -exec scripts/general/hash-filename.sh {} ';'
----

[#loop]
==== loop

link:scripts/general/loop.sh[This script] will invoke the given script repeatedly with a given delay between invocations and an initial delay.

The loop will finish when the given script has an exit code other than `100`.

===== Usage

.with-exit-condition.sh
[source,shell]
----
#!/usr/bin/env sh
if [ ... ]; then
  exit 0 # finish loop
fi
----

.infinite.sh
[source,shell]
----
#!/usr/bin/env sh
exit 100 # infinite loop
----

[source,shell]
----
$ scripts/general/loop.sh 10 10 some-script.sh
$ scripts/general/loop.sh 5 0 some-otherscript-with-parameters.sh a 1
----

===== Related Scripts

. <<counter,counter>>
+
[source,shell]
----
$ scripts/general/loop.sh 1 0 scripts/general/counter.sh my-counter 5
12345
----

[#shellscript-check]
==== shellscript-check

link:scripts/general/shellscript-check.sh[This script] will invoke https://www.shellcheck.net[shellcheck] on `*.sh` files in the given directory (`$PWD` if not given) and its subdirectories.

[NOTE]
====
`shellcheck` needs to be <<shellcheck,installed>>.
====

[TIP]
====
If you copy this script into a Node.js-based project you should exclude the `node_modules` directory:

`find … -name '*.sh' -not -path '*/node_modules/*' -print0 …`
====

===== Usage

[source,shell]
----
$ scripts/general/shellscript-check.sh
$ scripts/general/shellscript-check.sh /tmp
----

[#git-scripts]
=== Git

This section contains scripts related to https://git-scm.com[Git]:

<<git-cleanup,git-cleanup>>:: remove untracked files from the working tree and optimize a local repository

[#git-cleanup]
==== git-cleanup

link:scripts/git/git-cleanup.sh[This script] will do the following:

* remove untracked files from the working tree
* cleanup remote branches
* cleanup unnecessary files and optimize the local repository

It should be copied into a Git repository.

[WARNING]
====
This script will remove all untracked files.

Sometimes you have untracked files which you do not want to be cleaned up.

For example:

* `.env` or `.envrc` files
* `\*.crt`, `*.pem` or `*.key` self-signed certificate files
* IDE metadata

Add them to the https://+git-scm.com/docs/git-clean#Documentation/git-clean.txt--eltpatterngt+[exclusions] to ensure that they will not be removed:

.scripts/git-cleanup.sh
[source,shell,highlight=2,9]
----
  git clean -qfdx \
+  -e .env \
  -e .fleet \
  -e .idea \
  -e .classpath \
  -e .project \
  -e .settings \
  -e .vscode \
+  -e *.pem \
   .
----
====

[NOTE]
====
By default, the metadata files of https://eclipseide.org[Eclipse], https://www.jetbrains.com/products/#type=ide[JetBrains IDEs], and https://code.visualstudio.com[Visual Studio Code] are not removed.
====

===== Usage

[source,shell]
----
$ scripts/git/git-cleanup.sh
----

== Functions

The functions need to be copied into an https://docstore.mik.ua/orelly/unix3/upt/ch29_13.htm#upt3-CHP-29-SECT-13.2.2[$FPATH directory].

[IMPORTANT]
====
The filename needs to match the name of the function.
====

[TIP]
====
Example zsh setup:

[source,shell]
----
$ mkdir ~/.zfunc
----

.~/.zshrc
[source,shell]
----
readonly ext_func="${HOME}/.zfunc"

export FPATH="${ext_func}:${FPATH}"

for f in ${ext_func}; do
  # shellcheck disable=SC2046
  autoload -Uz $(ls "${f}")
done
----

The functions should be copied into `~/.zfunc`.
====

[#general-functions]
=== General

This section contains generally useful functions:

<<color_stderr,color_stderr>>:: color errors red
<<ls_extensions,ls_extensions>>:: displays all file extensions

[#color_stderr]
==== color_stderr

link:zfunc/color_stderr[This function] will display stderr output in red.

===== Usage

.with-stderr-output.sh
[source,shell]
----
#!/usr/bin/env sh
echo 'error' >&2
----

[source,shell,subs="quotes"]
----
$ color_stderr ./with-stderr-output.sh
[red]#error#
----

ifdef::env-github[]
[NOTE]
====
GitHub unfortunately does not show the "error" above in red.
====
endif::[]

[#ls_extensions]
==== ls_extensions

link:zfunc/ls_extensions[This function] will display all file extensions (case-insensitive) and their count in the given directory (`$PWD` if not given) and its subdirectories.

===== Usage

[source,shell]
----
$ ls_extensions
   5 sh
$ ls_extensions /tmp/example
   3 txt
   1 png
$ tree --noreport -a /tmp/example
/tmp/example
├── a.b.txt
├── a.txt
├── b.TXT
└── d
    ├── .ignored
    └── e.png
----

===== Related Functions

. <<ls_extensions_git,ls_extensions_git>>

[#git-functions]
=== Git

This section contains functions related to https://git-scm.com[Git]:

<<ls_extensions_git,ls_extensions_git>>:: display all file extensions for tracked files

[#ls_extensions_git]
==== ls_extensions_git

link:zfunc/ls_extensions_git[This function] will display all file extensions (case-insensitive) of tracked files and their count in the given Git directory (`$PWD` if not given) and its subdirectories.

[TIP]
====
This script, in conjunction with the <<ls_extensions,ls_extensions>> script, is helpful in determining whether you have covered your files properly in your https://git-scm.com/docs/gitattributes[.gitattributes] file.

[source,shell]
----
$ tree --noreport -a -I .git .
.
├── gradle
│   └── wrapper
│       └── gradle-wrapper.jar
└── gradlew.bat

$ ls_extensions
   1 jar
   1 bat

$ git check-attr -a gradlew.bat                                    <1>
$ git check-attr -a gradle/wrapper/gradle-wrapper.jar

$ printf '*.bat text eol=crlf\n*.jar binary\n' > .gitattributes    <2>
$ cat .gitattributes
*.bat text eol=crlf
*.jar binary

$ git check-attr -a gradlew.bat
gradlew.bat: text: set
gradlew.bat: eol: crlf
$ git check-attr -a gradle/wrapper/gradle-wrapper.jar
gradle/wrapper/gradle-wrapper.jar: binary: set
gradle/wrapper/gradle-wrapper.jar: diff: unset
gradle/wrapper/gradle-wrapper.jar: merge: unset
gradle/wrapper/gradle-wrapper.jar: text: unset

$ ls_extensions_git                                                <3>

$ git add gradlew.bat gradle/wrapper/gradle-wrapper.jar            <4>

$ ls_extensions_git                                                <5>
   1 jar
   1 bat
----
====

<1> Both `gradlew.bat` and `gradle-wrapper.jar` have no attributes set--if we would add them to the Git index at this point they would https://dev.to/deadlybyte/please-add-gitattributes-to-your-git-repository-1jld[not be handled properly] by Git.

<2> Add the appropriate attributes for JAR and Windows batch files.

<3> Nothing has been added to the Git index yet: So `ls_extensions_git` shows no file extensions.

<4> Add both files to the Git index.

<5> Both file extensions will be reported once they are in the Git index.

===== Usage

[source,shell]
----
$ ls_extensions_git
   5 sh
$ ls_extensions_git /tmp/example
   3 txt
   1 png
$ tree --noreport -a -I .git /tmp/example
/tmp/example
├── a.b.txt
├── a.txt
├── b.TXT
├── d
│   ├── .ignored
│   └── e.png
└── out.txt
$ git ls-files
a.b.txt
a.txt
b.txt
d/.ignored
d/e.png
----

===== Related Functions

. <<ls_extensions,ls_extensions>>

== License

Apache License, Version 2.0 (link:LICENSES/Apache-2.0.txt[Apache-2.0.txt] or {uri-apache-license}).

== Contribution

See link:CONTRIBUTING{outfilesuffix}[].

== Code of Conduct

We abide by the {uri-contributor-covenant}[Contributor Covenant, Version 2.1] and ask that you do as well.

For more information, please see link:CODE_OF_CONDUCT{outfilesuffix}[].

== Development Environment Setup

[IMPORTANT]
====
After initializing the repository you need to install the Git hooks via:

[source,shell]
----
$ git config core.hooksPath .githooks
----
====

=== Installation

[#shellcheck]
==== shellcheck

===== Linux

[source,shell]
----
$ sudo apt-get install shellcheck
----

===== Mac

[source,shell]
----
$ brew install shellcheck
----

[#yamllint]
==== yamllint

===== Linux

[source,shell]
----
$ sudo apt-get install yamllint
----

===== Mac

[source,shell]
----
$ brew install yamllint
----
