// SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
// SPDX-License-Identifier: Apache-2.0
= sdavids-shell-misc
Sebastian Davids <sdavids@gmx.de>
// Metadata:
:description: Miscellaneous shell-related scripts and functions.
// Settings:
:sectnums:
:sectanchors:
:sectlinks:
:toc: macro
:toclevels: 3
:toc-placement!:
:source-highlighter: rouge
:rouge-style: github
:docinfo: shared
:docinfodir: docs/asciidoc/docinfo
// Refs:
:uri-contributor-covenant: https://www.contributor-covenant.org
:uri-apache-license: https://www.apache.org/licenses/LICENSE-2.0
:uri-google-style: https://github.com/google/gts
:fnm-install-url: https://github.com/Schniz/fnm#installation
:gh-cli-install-url: https://github.com/cli/cli#linux--bsd
:nvm-install-url: https://github.com/nvm-sh/nvm#installing-and-updating

ifdef::env-browser[:outfilesuffix: .adoc]

ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:tip-caption: :bulb:
:warning-caption: :warning:
:badges:
endif::[]

ifdef::badges[]
image:https://img.shields.io/github/license/sdavids/sdavids-shell-misc[Apache License,Version 2.0,link={uri-apache-license}]
image:https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg[Contributor Covenant,Version 2.1,link={uri-contributor-covenant}]
image:https://img.shields.io/badge/code%20style-google-blueviolet.svg[Code Style: Google,link={uri-google-style}]
image:https://img.shields.io/osslifecycle/sdavids/sdavids-shell-misc[OSS Lifecycle]
image:https://img.shields.io/maintenance/yes/2024[Maintenance]
image:https://img.shields.io/github/last-commit/sdavids/sdavids-shell-misc[GitHub last commit]
image:http://isitmaintained.com/badge/resolution/sdavids/sdavids-shell-misc.svg[Resolution Time]
image:http://isitmaintained.com/badge/open/sdavids/sdavids-shell-misc.svg[Open Issues]
endif::[]

toc::[]

{description}

== Scripts

[#general-scripts]
=== General

This section contains generally useful scripts:

<<counter,counter>>:: create a counter
<<create-timestamp-file,create-timestamp-file>>:: create a file with a timestamp
<<loop,loop>>:: repeat a script repeatedly
<<hash-filename,hash-filename>>:: insert a hash into a filename
<<shellscript-check,shellscript-check>>:: shellcheck `*.sh` files in the given directory

[#counter]
==== counter

link:scripts/general/counter.sh[This script] will create a counter with the given name.

The optional second positive integer parameter will stop the counter when the current count is equal or larger than the given argument.

Invoking this script will print the current count to stdout unless the counter has been removed.

The exit code of the script will be `100` when the count has been increased or `0` when the counter has been removed.

The count is persisted in a file in a temporary directory or `COUNTER_DIR` if set in the environment.

===== Usage

.toggle.sh
[source,shell]
----
#!/usr/bin/env sh
scripts/general/counter.sh toggle 1 1>/dev/null
if [ $? -eq 100 ]; then
  echo 'on'
else
  echo 'off'
fi
----

.retry.sh
[source,shell]
----
#!/usr/bin/env sh
COUNTER_DIR="${XDG_STATE_HOME:=${HOME}}/retry" scripts/general/counter.sh retry 3 1>/dev/null
if [ $? -ne 100 ]; then
  echo 'tried enough times' >&2
  exit 50
fi
----

[source,shell]
----
$ scripts/general/counter.sh my-counter 2
1
$ echo $?
100
$ scripts/general/counter.sh my-counter 2
2
$ echo $?
100
$ scripts/general/counter.sh my-counter 2
$ echo $?
0
$ ./toggle.sh
on
$ ./toggle.sh
off
$ ./toggle.sh
on
$ mkdir -p "${XDG_STATE_HOME:=${HOME}}/retry"
$ ./retry.sh
$ ls "${XDG_STATE_HOME:=${HOME}}/retry"
counter-retry
$ cat /home/example/.local/state/retry/counter-retry
1
$ ./retry.sh
$ cat /home/example/.local/state/retry/counter-retry
2
$ ./retry.sh
$ cat /home/example/.local/state/retry/counter-retry
3
$ ./retry.sh
tried enough times
$ ls "${XDG_STATE_HOME:=${HOME}}/retry"
$ rm -rf "${XDG_STATE_HOME:=${HOME}}/retry"
----

===== Related Scripts

. <<loop,loop>>
+
[source,shell]
----
$ scripts/general/loop.sh 1 0 scripts/general/counter.sh my-counter 5
12345
----

[#create-timestamp-file]
==== create-timestamp-file

link:scripts/general/create-timestamp-file.sh[This script] will create a file with the given name; the content will be the https://www.rfc-editor.org/rfc/rfc3339[RFC 3339 timestamp] of the file's creation, e.g.:

[source]
----
2024-01-16T16:33:12Z
----

===== Usage

[source,shell]
----
$ scripts/general/create-timestamp-file.sh .timestamp
$ cat .timestamp
2024-02-19T10:37:02Z
----

[#hash-filename]
==== hash-filename

link:scripts/general/hash-filename.sh[This script] will rename a given file; the new filename will have a hash inserted, e.g.:

`test.txt` ⇒ `test.da39a3e.txt`

Use the optional second parameter `-e` to print the new filename to stdout.

===== Usage

[source,shell]
----
$ scripts/general/hash-filename.sh test.txt
$ scripts/general/hash-filename.sh test-echo.txt -e
test-echo.da39a3e.txt
$ find . \( -type f -name '*.jpg' -o -name '*.png' \) -exec scripts/general/hash-filename.sh {} ';'
----

[#loop]
==== loop

link:scripts/general/loop.sh[This script] will invoke the given script repeatedly with a given delay between invocations and an initial delay.

The loop will finish when the given script has an exit code other than `100`.

===== Usage

.with-exit-condition.sh
[source,shell]
----
#!/usr/bin/env sh
if [ ... ]; then
  exit 0 # finish loop
fi
----

.infinite.sh
[source,shell]
----
#!/usr/bin/env sh
exit 100 # infinite loop
----

[source,shell]
----
$ scripts/general/loop.sh 10 10 some-script.sh
$ scripts/general/loop.sh 5 0 some-otherscript-with-parameters.sh a 1
----

===== Related Scripts

. <<counter,counter>>
+
[source,shell]
----
$ scripts/general/loop.sh 1 0 scripts/general/counter.sh my-counter 5
12345
----

[#shellscript-check]
==== shellscript-check

link:scripts/general/shellscript-check.sh[This script] will invoke https://www.shellcheck.net[shellcheck] on `*.sh` files in the given directory (`$PWD` if not given) and its subdirectories.

[NOTE]
====
`shellcheck` needs to be <<shellcheck,installed>>.
====

[TIP]
====
If you copy this script into a Node.js-based project you should exclude the `node_modules` directory:

`find … -name '*.sh' -not -path '*/node_modules/*' -print0 …`
====

===== Usage

[source,shell]
----
$ scripts/general/shellscript-check.sh
$ scripts/general/shellscript-check.sh /tmp
----

[#git-scripts]
=== Git

This section contains scripts related to https://git-scm.com[Git]:

<<git-author-date-initial,git-author-date-initial>>:: displays the initial author dates of the committed files
<<git-author-date-last,git-author-date-last>>:: displays the last author dates of the committed files
<<git-cleanup,git-cleanup>>:: remove untracked files from the working tree and optimize a local repository
<<git-get-hash,git-get-hash>>:: return the hash of the HEAD commit
<<git-get-short-hash,git-get-short-hash>>:: return the short hash of the HEAD commit
<<git-is-working-tree-clean,git-is-working-tree-clean>>:: check whether the Git working tree  is clean

[#git-author-date-initial]
==== git-author-date-initial

link:scripts/git/git-author-date-initial.sh[This script] will display the initial https://git-scm.com/book/en/v2/Distributed-Git-Maintaining-a-Project#_git_am[author dates] of the files of the given Git repository directory (`$PWD` if not given).

If you use the optional second parameter then only the author date of the given file path will be displayed.

[NOTE]
====
The initial author date is the date the original author added and committed the file to the Git repository.
====

[TIP]
====
You can use this script to verify the initial publication year of your https://reuse.software/faq/#years-copyright[copyright statements].
====

===== Usage

[source,shell]
----
$ scripts/git/git-author-date-initial.sh /tmp/example
2022-04-16T15:59:50+02:00 a.txt
2022-04-16T15:59:50+02:00 b.txt
2022-04-16T16:00:14+02:00 c/d.txt
2023-04-16T16:00:41+02:00 e.txt
$ scripts/git/git-author-date-initial.sh /tmp/example | cut -c 1-4,26-
2022 a.txt
2022 b.txt
2022 c/d.txt
2023 e.txt
$ tree --noreport -a -I .git /tmp/example
/tmp/example
├── a.txt
├── b.txt
├── c
│   └── d.txt
└── e.txt
$ (cd /tmp/example && git --no-pager log --format=%aI --name-status)
2024-04-16T16:01:19+02:00

M       a.txt
2023-04-16T16:00:41+02:00

A       e.txt
2022-04-16T16:00:14+02:00

A       c/d.txt
2022-04-16T15:59:50+02:00

A       a.txt
A       b.txt
$ (cd /tmp/example && git --no-pager log --format=%aI --name-status a.txt)
2024-04-16T16:01:19+02:00

M       a.txt
2022-04-16T15:59:50+02:00

A       a.txt
----

===== Related Scripts

. <<git-author-date-last,git-author-date-last>>
+
[source,shell]
----
$ scripts/git/git-author-date-initial.sh /tmp/example
2022-04-16T15:59:50+02:00 a.txt
2022-04-16T15:59:50+02:00 b.txt
2022-04-16T16:00:14+02:00 c/d.txt
2023-04-16T16:00:41+02:00 e.txt
$ scripts/git/git-author-date-last.sh /tmp/example
2024-04-16T16:01:19+02:00 a.txt
2022-04-16T15:59:50+02:00 b.txt
2022-04-16T16:00:14+02:00 c/d.txt
2023-04-16T16:00:41+02:00 e.txt
$ scripts/git/git-author-date-initial.sh /tmp/example | cut -c 1-4,26- > initial.txt
$ scripts/git/git-author-date-last.sh /tmp/example | cut -c 1-4,26- > last.txt
$ diff initial.txt last.txt
1c1
< 2022 a.txt
---
> 2024 a.txt
----

[#git-author-date-last]
==== git-author-date-last

link:scripts/git/git-author-date-last.sh[This script] will display the last https://git-scm.com/book/en/v2/Distributed-Git-Maintaining-a-Project#_git_am[author dates] of the files of the given Git repository directory (`$PWD` if not given).

If you use the optional second parameter then only the author date of the given file path will be displayed.

[NOTE]
====
The last author date is the date of the last Git status change to a committed file of a Git repository.
====

[TIP]
====
You can use this script to verify the latest publication year of your https://reuse.software/faq/#years-copyright[copyright statements].
====

===== Usage

[source,shell]
----
$ scripts/git/git-author-date-last.sh /tmp/example
2024-04-16T16:01:19+02:00 a.txt
2022-04-16T15:59:50+02:00 b.txt
2022-04-16T16:00:14+02:00 c/d.txt
2023-04-16T16:00:41+02:00 e.txt
$ scripts/git/git-author-date-last.sh /tmp/example | cut -c 1-4,26-
2024 a.txt
2022 b.txt
2022 c/d.txt
2023 e.txt
$ scripts/git/git-author-date-last.sh /tmp/example a.txt
2024-04-16T16:01:19+02:00 a.txt
$ tree --noreport -a -I .git /tmp/example
/tmp/example
├── a.txt
├── b.txt
├── c
│   └── d.txt
└── e.txt
$ (cd /tmp/example && git --no-pager log --format=%aI --name-status)
2024-04-16T16:01:19+02:00

M       a.txt
2023-04-16T16:00:41+02:00

A       e.txt
2022-04-16T16:00:14+02:00

A       c/d.txt
2022-04-16T15:59:50+02:00

A       a.txt
A       b.txt
$ (cd /tmp/example && git --no-pager log --format=%aI --name-status a.txt)
2024-04-16T16:01:19+02:00

M       a.txt
2022-04-16T15:59:50+02:00

A       a.txt
----

===== Related Scripts

. <<git-author-date-initial,git-author-date-initial>>
+
[source,shell]
----
$ scripts/git/git-author-date-initial.sh /tmp/example
2022-04-16T15:59:50+02:00 a.txt
2022-04-16T15:59:50+02:00 b.txt
2022-04-16T16:00:14+02:00 c/d.txt
2023-04-16T16:00:41+02:00 e.txt
$ scripts/git/git-author-date-last.sh /tmp/example
2024-04-16T16:01:19+02:00 a.txt
2022-04-16T15:59:50+02:00 b.txt
2022-04-16T16:00:14+02:00 c/d.txt
2023-04-16T16:00:41+02:00 e.txt
$ scripts/git/git-author-date-initial.sh /tmp/example | cut -c 1-4,26- > initial.txt
$ scripts/git/git-author-date-last.sh /tmp/example | cut -c 1-4,26- > last.txt
$ diff initial.txt last.txt
1c1
< 2022 a.txt
---
> 2024 a.txt
----

[#git-cleanup]
==== git-cleanup

link:scripts/git/git-cleanup.sh[This script] will do the following:

* remove untracked files from the working tree
* cleanup remote branches
* cleanup unnecessary files and optimize the local repository

It should be copied into a Git repository.

[WARNING]
====
This script will remove all untracked files.

Sometimes you have untracked files which you do not want to be cleaned up.

For example:

* `.env` or `.envrc` files
* `\*.crt`, `*.pem` or `*.key` self-signed certificate files
* IDE metadata

Add them to the https://+git-scm.com/docs/git-clean#Documentation/git-clean.txt--eltpatterngt+[exclusions] to ensure that they will not be removed:

.scripts/git-cleanup.sh
[source,shell,highlight=2,9]
----
  git clean -qfdx \
+  -e .env \
  -e .fleet \
  -e .idea \
  -e .classpath \
  -e .project \
  -e .settings \
  -e .vscode \
+  -e *.pem \
   .
----
====

[NOTE]
====
By default, the metadata files of https://eclipseide.org[Eclipse], https://www.jetbrains.com/products/#type=ide[JetBrains IDEs], and https://code.visualstudio.com[Visual Studio Code] are not removed.
====

===== Usage

[source,shell]
----
$ scripts/git/git-cleanup.sh
----

[#git-get-hash]
==== git-get-hash

link:scripts/git/git-get-hash.sh[This script] will return the hash of the HEAD commit of the checked out branch of the given Git repository directory (`$PWD` if not given).

The suffix `-dirty` will be appended if the working tree is dirty.

===== Usage

[source,shell]
----
$ scripts/git/git-get-hash.sh
844881d148be35d7c0a9bcbf5ba23ab79cf14c6e
$ touch a
$ scripts/git/git-get-hash.sh
844881d148be35d7c0a9bcbf5ba23ab79cf14c6e-dirty
----

[#git-get-short-hash]
==== git-get-short-hash

link:scripts/git/git-get-short-hash.sh[This script] will return the https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt---shortlength[short hash] of the HEAD commit of the checked out branch of the given Git repository directory (`$PWD` if not given).

The suffix `-dirty` will be appended if the working tree is dirty.

The length of the hash can be configured via the optional second parameter (range: [4, 40] for https://git-scm.com/docs/gitrevisions#Documentation/gitrevisions.txt-emltsha1gtemegemdae86e1950b1277e545cee180551750029cfe735ememdae86eem[SHA-1 object names] or [4, 64] for https://git-scm.com/docs/hash-function-transition/#_object_names[SHA-256 object names]); the default is determined by the `core.abbrev` https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreabbrev[Git configuration variable].

[TIP]
====
To get a consistent hash length across systems you should either

[upperalpha]
. ensure that `core.abbrev` is set on the repository after initialization:
+
[source,shell]
----
$ git config --local core.abbrev 20
----
+
Unfortunately, these settings are https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_git_config[not under version control].

. explicitly set the length when invoking the script:
+
[source,shell]
----
$ scripts/git/git-get-short-hash.sh . 20
----
====

===== Usage

[source,shell]
----
$ scripts/git/git-get-short-hash.sh
437f01f
$ scripts/git/git-get-short-hash.sh path/to/git/repository
dbd0ffb
$ scripts/git/git-get-short-hash.sh . 10
437f01f904
$ git config --local core.abbrev 20
$ scripts/git/git-get-short-hash.sh
437f01f904c1c2839408
$ touch a
$ scripts/git/git-get-short-hash.sh
437f01f904c1c2839408-dirty
----

[#git-is-working-tree-clean]
==== git-is-working-tree-clean

link:scripts/git/git-is-working-tree-clean.sh[This script] will check whether the Git working tree in the given directory (`$PWD` if not given) is https://git-scm.com/docs/git-clean#_description[clean].

===== Usage

[source,shell]
----
$ scripts/git/git-is-working-tree-clean.sh
$ echo $?
----

0:: the Git working tree of the given directory is clean
1:: the Git working tree of the given directory is dirty
2:: the given directory is not a Git repository

[#web-scripts]
=== Web

This section contains scripts related to Web development:

<<compress-brotli,compress-brotli>>:: compress a file with brotli
<<compress-gzip,compress-gzip>>:: compress a file with gzip
<<compress-zstd,compress-zstd>>:: compress a file with zstd
<<minify-css,minify-css>>:: minify CSS files
<<minify-html,minify-html>>:: minify HTML files
<<minify-json,minify-json>>:: minify JSON files
<<minify-json-tags,minify-json-tags>>:: minify JSON-structured script tags
<<minify-robots,minify-robots>>:: minify the robots.txt file
<<minify-svg,minify-svg>>:: minify SVG files
<<minify-traffic-advice,minify-traffic-advice>>:: minify the private prefetch proxy traffic control file
<<minify-webmanifest,minify-webmanifest>>:: minify the web application manifest
<<minify-xml,minify-xml>>:: minify XML files

[#compress-brotli]
==== compress-brotli

link:scripts/web/compress-brotli.sh[This script] will compress the given file with https://github.com/google/brotli[brotli].

[NOTE]
====
`brotli` needs to be <<brotli,installed>>.
====

[TIP]
====
Here is a fragment to be placed into your `.htaccess` or https://httpd.apache.org/docs/current/configuring.html[Apache HTTPD server configuration file]:

[source]
----
<IfModule mod_headers.c>
  RewriteCond "%{HTTP:Accept-encoding}" "br"
  RewriteCond "%{REQUEST_FILENAME}.br" -s
  RewriteRule "^(.*)\.(css|html|js|mjs|svg)$" "/$1.$2.br" [QSA]

  RewriteRule "\.css\.br$" "-" [T=text/css,E=no-brotli:1,E=no-gzip:1,E=no-zstd:1]
  RewriteRule "\.html\.br$" "-" [T=text/html,E=no-brotli:1,E=no-gzip:1,E=no-zstd:1]
  RewriteRule "\.js\.br$" "-" [T=text/javascript,E=no-brotli:1,E=no-gzip:1,E=no-zstd:1]
  RewriteRule "\.mjs\.br$" "-" [T=text/javascript,E=no-brotli:1,E=no-gzip:1,E=no-zstd:1]
  RewriteRule "\.svg\.br$" "-" [T=text/javascript,E=no-brotli:1,E=no-gzip:1,E=no-zstd:1]

  <FilesMatch "(\.css|\.html|\.js|\.mjs|\.svg)\.br$">
    Header append Content-Encoding br
    Header append Vary Accept-Encoding
  </FilesMatch>
</IfModule>
----
====

===== Usage

[source,shell]
----
$ scripts/web/compress-brotli.sh test.txt
$ find dist \( -type f -name '*.html' -o -name '*.css' \) -exec scripts/web/compress-brotli.sh {} ';'
----

[#compress-gzip]
==== compress-gzip

link:scripts/web/compress-gzip.sh[This script] will compress the given file with gzip.

[TIP]
====
Here is a fragment to be placed into your `.htaccess` or https://httpd.apache.org/docs/current/configuring.html[Apache HTTPD server configuration file]:

[source]
----
<IfModule mod_headers.c>
  RewriteCond "%{HTTP:Accept-encoding}" "gzip"
  RewriteCond "%{REQUEST_FILENAME}.gz" -s
  RewriteRule "^(.*)\.(css|html|js|mjs|svg)$" "/$1.$2.gz" [QSA]

  RewriteRule "\.css\.gz$" "-" [T=text/css,E=no-brotli:1,E=no-gzip:1,E=no-zstd:1]
  RewriteRule "\.html\.gz$" "-" [T=text/html,E=no-brotli:1,E=no-gzip:1,E=no-zstd:1]
  RewriteRule "\.js\.gz$" "-" [T=text/javascript,E=no-brotli:1,E=no-gzip:1,E=no-zstd:1]
  RewriteRule "\.mjs\.gz$" "-" [T=text/javascript,E=no-brotli:1,E=no-gzip:1,E=no-zstd:1]
  RewriteRule "\.svg\.gz$" "-" [T=text/javascript,E=no-brotli:1,E=no-gzip:1,E=no-zstd:1]

  <FilesMatch "(\.css|\.html|\.js|\.mjs|\.svg)\.gz$">
    Header append Content-Encoding gzip
    Header append Vary Accept-Encoding
  </FilesMatch>
</IfModule>
----
====

===== Usage

[source,shell]
----
$ scripts/web/compress-gzip.sh test.txt
$ find dist \( -type f -name '*.html' -o -name '*.css' \) -exec scripts/web/compress-gzip.sh {} ';'
----

[#compress-zstd]
==== compress-zstd

link:scripts/web/compress-zstd.sh[This script] will compress the given file with https://github.com/facebook/zstd[zstd].

[NOTE]
====
`zstd` needs to be <<zstd,installed>>.
====

[TIP]
====
Here is a fragment to be placed into your `.htaccess` or https://httpd.apache.org/docs/current/configuring.html[Apache HTTPD server configuration file]:

[source]
----
<IfModule mod_headers.c>
  RewriteCond "%{HTTP:Accept-encoding}" "zstd"
  RewriteCond "%{REQUEST_FILENAME}.zst" -s
  RewriteRule "^(.*)\.(css|html|js|mjs|svg)$" "/$1.$2.zst" [QSA]

  RewriteRule "\.css\.zst$" "-" [T=text/css,E=no-brotli:1,E=no-gzip:1,E=no-zstd:1]
  RewriteRule "\.html\.zst$" "-" [T=text/html,E=no-brotli:1,E=no-gzip:1,E=no-zstd:1]
  RewriteRule "\.js\.zst$" "-" [T=text/javascript,E=no-brotli:1,E=no-gzip:1,E=no-zstd:1]
  RewriteRule "\.mjs\.zst$" "-" [T=text/javascript,E=no-brotli:1,E=no-gzip:1,E=no-zstd:1]
  RewriteRule "\.svg\.zst$" "-" [T=text/javascript,E=no-brotli:1,E=no-gzip:1,E=no-zstd:1]

  <FilesMatch "(\.css|\.html|\.js|\.mjs|\.svg)\.zst$">
    Header append Content-Encoding zstd
    Header append Vary Accept-Encoding
  </FilesMatch>
</IfModule>
----
====

===== Usage

[source,shell]
----
$ scripts/web/compress-zstd.sh test.txt
$ find dist \( -type f -name '*.html' -o -name '*.css' \) -exec scripts/web/compress-zstd.sh {} ';'
----

[#minify-css]
==== minify-css

link:scripts/web/minify-css.sh[This script] will minify and transpile the `*.css` files in the given directory (`$PWD` if not given) and its subdirectories.

This script uses https://github.com/browserslist/browserslist[browserslist] to determine the transpilation targets.

[NOTE]
====
`npx` needs to be <<node-version-manager,installed>>.
====

[TIP]
====
If you do not want the https://browserslist.dev/?q=ZGVmYXVsdHM%3D[defaults] you have https://lightningcss.dev/transpilation.html#cli[several options] to change them.

For example via the following file:

..browserslistrc
[source]
----
last 2 versions
----
====

===== Usage

[source,shell]
----
$ scripts/web/minify-css.sh
$ scripts/web/minify-css.sh dist
----

[#minify-html]
==== minify-html

link:scripts/web/minify-html.sh[This script] will minify the `*.html` files in the given directory (`$PWD` if not given) and its subdirectories.

[NOTE]
====
`npx` needs to be <<node-version-manager,installed>>.
====

===== Usage

[source,shell]
----
$ scripts/web/minify-html.sh
$ scripts/web/minify-html.sh dist
----

[#minify-json]
==== minify-json

link:scripts/web/minify-json.sh[This script] will minify the `*.json` files in the given directory (`$PWD` if not given) and its subdirectories.

[NOTE]
====
`jq` needs to be <<jq,installed>>.
====

===== Usage

[source,shell]
----
$ scripts/web/minify-json.sh
$ scripts/web/minify-json.sh dist
----

[#minify-json-tags]
==== minify-json-tags

link:scripts/web/minify-json-tags.mjs[This script] will minify JSON-structured script tags in the given HTML file.

[source,html]
----
<html>
…
  <script type="importmap">
    {
      "imports": {
        "utils": "/j/utils.mjs"
      }
    }
  </script>
  <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "Organization",
      "url": "https://sdavids.de/"
    }
  </script>
…
</html>
----

⇓

[source,html]
----
<html>
…
<script type="importmap">{"imports":{"utils":"/j/utils.mjs"}}</script>
<script type="application/ld+json">{"@context":"https://schema.org","@type":"Organization","url":"https://sdavids.de/"}</script>
…
</html>
----

[NOTE]
====
`npm` needs to be <<node-version-manager,installed>>.

Afterward, you need to install the dependencies of this script:

[source,shell]
----
$ npm i --save-dev domutils dom-serializer htmlparser2
----

====

===== Usage

[source,shell]
----
$ scripts/web/minify-json-tags.mjs dist/index.html
$ find dist -type f -name '*.html' -exec scripts/web/minify-json-tags.mjs {} ';'
----

[#minify-robots]
==== minify-robots

link:scripts/web/minify-robots.sh[This script] will minify the `robots.txt` file in the given directory (`$PWD` if not given).

===== Usage

[source,shell]
----
$ scripts/web/minify-html.sh
$ scripts/web/minify-robots.sh dist
----

[#minify-svg]
==== minify-svg

link:scripts/web/minify-svg.sh[This script] will minify the `*.svg` files in the given directory (`$PWD` if not given) and its subdirectories.

[NOTE]
====
`npx` needs to be <<node-version-manager,installed>>.
====

[TIP]
====
If you are using macOS you might want to use https://imageoptim.com/mac[ImageOptim] instead of using this script.
====

[TIP]
====
It is advisable to minimize image files before adding them to a Git repository.

Minimizing image files during a build is usually bad idea unless the build generates images files.

Also, you might want to add a <<hash-filename,hash>> to the minified image file before adding it to a Git repository.
====

===== Usage

[source,shell]
----
$ scripts/web/minify-svg.sh
$ scripts/web/minify-svg.sh dist
----

[#minify-traffic-advice]
==== minify-traffic-advice

link:scripts/web/minify-traffic-advice.sh[This script] will minify the https://developer.chrome.com/blog/private-prefetch-proxy/#traffic[private prefetch proxy traffic control] file.

[NOTE]
====
`jq` needs to be <<jq,installed>>.
====

===== Usage

[source,shell]
----
$ scripts/web/minify-traffic-advice.sh dist/.well-known/traffic-advice
----

[#minify-webmanifest]
==== minify-webmanifest

link:scripts/web/minify-webmanifest.sh[This script] will minify the given https://developer.mozilla.org/en-US/docs/Web/Manifest[web application manifest] file.

[NOTE]
====
`jq` needs to be <<jq,installed>>.
====

===== Usage

[source,shell]
----
$ scripts/web/minify-webmanifest.sh dist/site.webmanifest
----

[#minify-xml]
==== minify-xml

link:scripts/web/minify-xml.sh[This script] will minify the `*.xml` files in the given directory (`$PWD` if not given) and its subdirectories.

[NOTE]
====
`npx` needs to be <<node-version-manager,installed>>.
====

===== Usage

[source,shell]
----
$ scripts/web/minify-xml.sh
$ scripts/web/minify-xml.sh dist
----

== Functions

The functions need to be copied into an https://docstore.mik.ua/orelly/unix3/upt/ch29_13.htm#upt3-CHP-29-SECT-13.2.2[$FPATH directory].

[IMPORTANT]
====
The filename needs to match the name of the function.
====

[TIP]
====
Example zsh setup:

[source,shell]
----
$ mkdir ~/.zfunc
----

.~/.zshrc
[source,shell]
----
readonly ext_func="${HOME}/.zfunc"

export FPATH="${ext_func}:${FPATH}"

for f in ${ext_func}; do
  # shellcheck disable=SC2046
  autoload -Uz $(ls "${f}")
done
----

The functions should be copied into `~/.zfunc`.
====

[#general-functions]
=== General

This section contains generally useful functions:

<<color_stderr,color_stderr>>:: color errors red
<<ls_extensions,ls_extensions>>:: displays all file extensions

[#color_stderr]
==== color_stderr

link:zfunc/color_stderr[This function] will display stderr output in red.

===== Usage

.with-stderr-output.sh
[source,shell]
----
#!/usr/bin/env sh
echo 'error' >&2
----

[source,shell,subs="quotes"]
----
$ color_stderr ./with-stderr-output.sh
[red]#error#
----

ifdef::env-github[]
[NOTE]
====
GitHub unfortunately does not show the "error" above in red.
====
endif::[]

[#ls_extensions]
==== ls_extensions

link:zfunc/ls_extensions[This function] will display all file extensions (case-insensitive) and their count in the given directory (`$PWD` if not given) and its subdirectories.

===== Usage

[source,shell]
----
$ ls_extensions
   5 sh
$ ls_extensions /tmp/example
   3 txt
   1 png
$ tree --noreport -a /tmp/example
/tmp/example
├── a.b.txt
├── a.txt
├── b.TXT
└── d
    ├── .ignored
    └── e.png
----

===== Related Functions

. <<ls_extensions_git,ls_extensions_git>>

[#git-functions]
=== Git

This section contains functions related to https://git-scm.com[Git]:

<<ls_extensions_git,ls_extensions_git>>:: display all file extensions for tracked files

[#ls_extensions_git]
==== ls_extensions_git

link:zfunc/ls_extensions_git[This function] will display all file extensions (case-insensitive) of tracked files and their count in the given Git directory (`$PWD` if not given) and its subdirectories.

[TIP]
====
This script, in conjunction with the <<ls_extensions,ls_extensions>> script, is helpful in determining whether you have covered your files properly in your https://git-scm.com/docs/gitattributes[.gitattributes] file.

[source,shell]
----
$ tree --noreport -a -I .git .
.
├── gradle
│   └── wrapper
│       └── gradle-wrapper.jar
└── gradlew.bat

$ ls_extensions
   1 jar
   1 bat

$ git check-attr -a gradlew.bat                                    <1>
$ git check-attr -a gradle/wrapper/gradle-wrapper.jar

$ printf '*.bat text eol=crlf\n*.jar binary\n' > .gitattributes    <2>
$ cat .gitattributes
*.bat text eol=crlf
*.jar binary

$ git check-attr -a gradlew.bat
gradlew.bat: text: set
gradlew.bat: eol: crlf
$ git check-attr -a gradle/wrapper/gradle-wrapper.jar
gradle/wrapper/gradle-wrapper.jar: binary: set
gradle/wrapper/gradle-wrapper.jar: diff: unset
gradle/wrapper/gradle-wrapper.jar: merge: unset
gradle/wrapper/gradle-wrapper.jar: text: unset

$ ls_extensions_git                                                <3>

$ git add gradlew.bat gradle/wrapper/gradle-wrapper.jar            <4>

$ ls_extensions_git                                                <5>
   1 jar
   1 bat
----
====

<1> Both `gradlew.bat` and `gradle-wrapper.jar` have no attributes set--if we would add them to the Git index at this point they would https://dev.to/deadlybyte/please-add-gitattributes-to-your-git-repository-1jld[not be handled properly] by Git.

<2> Add the appropriate attributes for JAR and Windows batch files.

<3> Nothing has been added to the Git index yet: So `ls_extensions_git` shows no file extensions.

<4> Add both files to the Git index.

<5> Both file extensions will be reported once they are in the Git index.

===== Usage

[source,shell]
----
$ ls_extensions_git
   5 sh
$ ls_extensions_git /tmp/example
   3 txt
   1 png
$ tree --noreport -a -I .git /tmp/example
/tmp/example
├── a.b.txt
├── a.txt
├── b.TXT
├── d
│   ├── .ignored
│   └── e.png
└── out.txt
$ git ls-files
a.b.txt
a.txt
b.txt
d/.ignored
d/e.png
----

===== Related Functions

. <<ls_extensions,ls_extensions>>

[#github-cli]
=== GitHub CLI

This section contains functions related to https://cli.github.com[GitHub CLI]:

<<repo_new_gh,repo_new_gh>>:: create and checkout a private GitHub repository
<<repo_new_local,repo_new_local>>:: create a new local repository based on a GitHub template repository

[#repo_new_gh]
==== repo_new_gh

link:zfunc/repo_new_gh[This function] will create and checkout a new private GitHub repository from a https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository[GitHub template repository] with the given name.

[IMPORTANT]
====
You should change the template being used:

.zfunc/repo_new_gh
[source,shell]
----
- readonly template='sdavids/sdavids-project-template'
+ readonly template='my-github-user/my-template'
----
====

[NOTE]
====
`GitHub CLI` needs to be <<gh-cli,installed>>.
====

[NOTE]
====
This script uses https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work[Git commit signing]; you need to:

* configure your https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key#telling-git-about-your-gpg-key[local git
config]
* https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account#adding-a-gpg-key[add your public GPG key] to GitHub

Alternatively, you can remove `--gpg-sign`:

.zfunc/repo_new_gh
[source,shell,highlight=3]
----
  git commit \
    --quiet \
-   --gpg-sign \
    --signoff \
----
====

===== Usage

[source,shell]
----
$ repo_new_gh my-new-repo
----

[#repo_new_local]
==== repo_new_local

link:zfunc/repo_new_local[This function] will create a new local repository based on a https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository[GitHub template repository] with the given name.

[IMPORTANT]
====
This function needs the GitHub `delete_repo` permission.

[source,shell]
----
$ gh auth refresh -h github.com -s delete_repo
----
====

[IMPORTANT]
====
You should change the GitHub user and template being used:

.zfunc/repo_new_local
[source,shell,highlight=2,4]
----
- readonly template='sdavids/sdavids-project-template'
+ readonly template='my-github-user/my-template'
- readonly gh_user_id='sdavids'
+ readonly gh_user_id='my-github-user'
----
====

[NOTE]
====
`GitHub CLI` needs to be <<gh-cli,installed>>.
====

[NOTE]
====
This script uses https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work[Git commit signing];  you need to configure your https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key#telling-git-about-your-gpg-key[local git config].

Alternatively, you can remove `--gpg-sign`:

.zfunc/repo_new_local
[source,shell,highlight=3]
----
  git commit \
    --quiet \
-   --gpg-sign \
    --signoff \
----
====

===== Usage

[source,shell]
----
$ repo_new_local my-new-local-repo
----

== License

Apache License, Version 2.0 (link:LICENSES/Apache-2.0.txt[Apache-2.0.txt] or {uri-apache-license}).

== Contribution

See link:CONTRIBUTING{outfilesuffix}[].

== Code of Conduct

We abide by the {uri-contributor-covenant}[Contributor Covenant, Version 2.1] and ask that you do as well.

For more information, please see link:CODE_OF_CONDUCT{outfilesuffix}[].

== Development Environment Setup

[IMPORTANT]
====
After initializing the repository you need to install the Git hooks via:

[source,shell]
----
$ git config core.hooksPath .githooks
----
====

=== Installation

[#brotli]
==== brotli

===== Linux

[source,shell]
----
$ sudo apt-get install brotli
----

===== Mac

[source,shell]
----
$ brew install brotli
----

[#gh-cli]
==== GitHub CLI

===== Linux

Install {gh-cli-install-url}[GitHub CLI].

===== Mac

[source,shell]
----
$ brew install gh
----

[#jq]
==== jq

===== Linux

[source,shell]
----
$ sudo apt-get install jq
----

===== Mac

[source,shell]
----
$ brew install jq
----

[#node-version-manager]
==== Node Version Manager

Install {fnm-install-url}[fnm] or {nvm-install-url}[NVM].

===== fnm

.~/.zprofile
[source,shell]
----
if command -v fnm > /dev/null 2>&1; then
  eval "$(fnm env --use-on-cd)"
fi
----

===== nvm

.~/.zshrc
[source,shell]
----
export NVM_DIR="${HOME}/.nvm"

[ -s "${NVM_DIR}/nvm.sh" ] && . "${NVM_DIR}/nvm.sh"
[ -s "${NVM_DIR}/bash_completion" ] && . "${NVM_DIR}/bash_completion"

if command -v nvm > /dev/null 2>&1; then
  autoload -U add-zsh-hook
  load-nvmrc() {
    local nvmrc_path="$(nvm_find_nvmrc)"
    if [ -n "${nvmrc_path}" ]; then
      local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")
      if [ "${nvmrc_node_version}" = "N/A" ]; then
        nvm install
      elif [ "${nvmrc_node_version}" != "$(nvm version)" ]; then
        nvm use
      fi
    elif [ -n "$(PWD=$OLDPWD nvm_find_nvmrc)" ] && [ "$(nvm version)" != "$(nvm version default)" ]; then
      echo "Reverting to nvm default version"
      nvm use default
    fi
  }

  add-zsh-hook chpwd load-nvmrc
  load-nvmrc
fi
----

[#shellcheck]
==== shellcheck

===== Linux

[source,shell]
----
$ sudo apt-get install shellcheck
----

===== Mac

[source,shell]
----
$ brew install shellcheck
----

[#yamllint]
==== yamllint

===== Linux

[source,shell]
----
$ sudo apt-get install yamllint
----

===== Mac

[source,shell]
----
$ brew install yamllint
----

[#zstd]
==== zstd

===== Linux

[source,shell]
----
$ sudo apt install zstd
----

===== Mac

[source,shell]
----
$ brew install zstd
----
