# SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
# SPDX-License-Identifier: Apache-2.0

version = 1

SPDX-PackageName = "sdavids-shell-misc"
SPDX-PackageSupplier = "Sebastian Davids <sdavids@gmx.de>"
SPDX-PackageDownloadLocation = "https://github.com/sdavids/sdavids-shell-misc"

[[annotations]]
path = "**/**.png"
SPDX-FileCopyrightText = "© 2024 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docs/asciidoc/docinfo/docinfo.html"
SPDX-FileCopyrightText = "© 2024 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/gradlew"
SPDX-FileCopyrightText = "© 2015-2021 the original authors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["**/gradle-wrapper.jar", "**/gradle-wrapper.properties", "**/gradlew.bat"]
SPDX-FileCopyrightText = "© 2015 the original author or authors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["**/gradle-daemon-jvm.properties"]
SPDX-FileCopyrightText = "© 2024 the original author or authors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "scripts/cert/js/nodejs/.nvmrc"
SPDX-FileCopyrightText = "© 2024 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "scripts/asciidoc/example-html/src/_includes/*.adoc"
SPDX-FileCopyrightText = "© 2024 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "scripts/asciidoc/example-html/src/docinfo/*.html"
SPDX-FileCopyrightText = "© 2024 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "scripts/asciidoc/example-html/src/css/font-awesome.css"
SPDX-FileCopyrightText = "© 2012 Dave Gandy (http://fontawesome.io)"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "scripts/asciidoc/example-html/src/fonts/fontawesome-webfont-4.7.0.woff2"
SPDX-FileCopyrightText = "© 2012 Dave Gandy (http://fontawesome.io)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "scripts/asciidoc/example-html/src/fonts/source-code-pro-**"
SPDX-FileCopyrightText = "© 2010, 2012 Adobe Systems Incorporated (http://www.adobe.com/)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "scripts/asciidoc/example-html/src/fonts/source-sans-3-**"
SPDX-FileCopyrightText = "© 2010-2020 Adobe (http://www.adobe.com/)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "scripts/asciidoc/example-html/src/fonts/source-serif-4-**"
SPDX-FileCopyrightText = "© 2014 - 2023 Adobe (http://www.adobe.com/)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = [
  "scripts/asciidoc/example-html/src/src/csv/data.csv",
  "scripts/asciidoc/example-pdf/src/src/csv/data.csv",
]
SPDX-FileCopyrightText = "© 2024 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "scripts/asciidoc/example-html/src/images/dragonfly.jpg",
  "scripts/asciidoc/example-pdf/src/images/dragonfly.jpg",
]
SPDX-FileCopyrightText = "© 2017 Charles J. Sharp (https://www.sharpphotography.co.uk)"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "scripts/asciidoc/example-pdf/src/_includes/*.adoc"
SPDX-FileCopyrightText = "© 2024 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docs/user-guide/modules/ROOT/attachments/asciidoc/main.pdf"
SPDX-FileCopyrightText = "© 2024 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docs/user-guide/modules/ROOT/attachments/latex/main.pdf"
SPDX-FileCopyrightText = "© 2024 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "scripts/asciidoc/example-pdf/src/fonts/MPlus1mn-**",
]
SPDX-FileCopyrightText = "© 2002-2019 The M+ FONTS Project Authors"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = [
  "scripts/asciidoc/example-pdf/src/fonts/NotoEmoji-Regular.ttf",
]
SPDX-FileCopyrightText = "© 2013 Google LLC"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = [
  "scripts/asciidoc/example-pdf/src/fonts/SourceCodePro-**",
  "scripts/latex/example/src/fonts/SourceCodePro-**",
]
SPDX-FileCopyrightText = "© 2010, 2012 Adobe Systems Incorporated (http://www.adobe.com/)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = [
  "scripts/asciidoc/example-pdf/src/fonts/SourceSans3-**",
  "scripts/latex/example/src/fonts/SourceSans3-**",
]
SPDX-FileCopyrightText = "© 2010-2020 Adobe (http://www.adobe.com/)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = [
  "scripts/asciidoc/example-pdf/src/fonts/SourceSerif4-**",
  "scripts/latex/example/src/fonts/SourceSerif4-**",
]
SPDX-FileCopyrightText = "© 2014 - 2023 Adobe (http://www.adobe.com/)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "docs/ui-bundle/**"
SPDX-FileCopyrightText = "© 2017-2024 OpenDevise Inc. and the Antora Project; © 2024 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "MPL-2.0"
