# SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
# SPDX-License-Identifier: Apache-2.0

version = 1

SPDX-PackageName = "sdavids-shell-misc"
SPDX-PackageSupplier = "Sebastian Davids <sdavids@gmx.de>"
SPDX-PackageDownloadLocation = "https://github.com/sdavids/sdavids-shell-misc"

[[annotations]]
path = "OSSMETADATA"
SPDX-FileCopyrightText = "© 2024 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/**.png"
SPDX-FileCopyrightText = "© 2024 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docs/asciidoc/docinfo/docinfo.html"
SPDX-FileCopyrightText = "© 2024 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/gradlew"
SPDX-FileCopyrightText = "© 2015-2021 the original authors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["**/gradle-wrapper.jar", "**/gradle-wrapper.properties", "**/gradlew.bat"]
SPDX-FileCopyrightText = "© 2015 the original author or authors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "scripts/cert/js/nodejs/.nvmrc"
SPDX-FileCopyrightText = "© 2024 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"
