// SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
// SPDX-License-Identifier: Apache-2.0
= Installation
:docker-install-url: https://docs.docker.com/install/
:easyrsa-install-url: https://easy-rsa.readthedocs.io/en/latest/#obtaining-and-using-easy-rsa
:fnm-install-url: https://github.com/Schniz/fnm#installation
:gh-cli-install-url: https://github.com/cli/cli#linux--bsd
:hadolint-install-url: https://github.com/hadolint/hadolint?tab=readme-ov-file#install
:nvm-install-url: https://github.com/nvm-sh/nvm#installing-and-updating
:oxipng-install-url: https://github.com/shssoichiro/oxipng/issues/69
:pnpm-install-url: https://pnpm.io/installation

[#brotli]
== brotli

=== Linux

[,console]
----
$ sudo apt-get install brotli
----

=== Mac

[,console]
----
$ brew install brotli
----

[#curl]
== curl

=== Linux

[,console]
----
$ sudo apt-get install curl
----

=== Mac

`curl` is part of the standard macOS installation.

[#docker]
== Docker

Install {docker-install-url}[Docker].

[#easyrsa]
== EasyRSA

[IMPORTANT]
====
Ensure that you install version `3.1.7` and not `3.2.x`!
====

=== Linux

Install {easyrsa-install-url}[EasyRSA].

=== Mac

[WARNING]
====
Unfortunately, _homebrew_ provides `easy-rsa` version `3.2.x`.
====

[,console]
----
$ curl -L https://github.com/OpenVPN/easy-rsa/releases/download/v3.1.7/EasyRSA-3.1.7.tgz -o ~/Downloads/easy-rsa.tgz
$ tar -xzf ~/Downloads/easy-rsa.tgz -C ~/.local/share
$ mv  ~/.local/share/EasyRSA-3.1.7 ~/.local/share/easyrsa
$ ln -s ~/.local/share/easyrsa/easyrsa ~/.local/bin/easyrsa
$ rm ~/Downloads/easy-rsa.tgz
----

[#exiftool]
== exiftool

=== Linux

[,console]
----
$ sudo apt-get install exiftool
----

=== Mac

[,console]
----
$ brew install exiftool
----

[#gifsicle]
== gifsicle

=== Linux

[,console]
----
$ sudo apt-get install gifsicle
----

=== Mac

[,console]
----
$ brew install gifsicle
----

[#gh-cli]
== GitHub CLI

=== Linux

Install {gh-cli-install-url}[GitHub CLI].

=== Mac

[,console]
----
$ brew install gh
----

[#gradle]
== Gradle

First <<jdk,install a JDK>>.

There are https://gradle.org/install/[multiple options] for installing Gradle.

The recommended way is to https://sdkman.io/install[install via SDKMAN!]:

[,console]
----
$ sdk install gradle
----

[#gzip]
== gzip

=== Linux

[,console]
----
$ sudo apt-get install gzip
----

=== Mac

[,console]
----
$ brew install gzip
----

== hadolint

=== Linux

Install {hadolint-install-url}[hadolint].

=== Mac

[,console]
----
$ brew install hadolint
----

[#jdk]
== JDK

There are https://whichjdk.com[several different JDKs] and multiple options for installing them.

The https://whichjdk.com/#what-is-the-best-way-to-install-a-jdk-for-local-development[recommended] way is to https://sdkman.io/install[install via SDKMAN!]:

[,console]
----
$ sdk install java
----

=== More Information

https://sdkman.io/jdks[SDKMAN JDKs]

[#jpegoptim]
== jpegoptim

=== Linux

[,console]
----
$ sudo apt-get install jpegoptim
----

=== Mac

[,console]
----
$ brew install jpegoptim
----

[#jq]
== jq

=== Linux

[,console]
----
$ sudo apt-get install jq
----

=== Mac

[,console]
----
$ brew install jq
----

[#node-version-manager]
== Node Version Manager

Install {fnm-install-url}[fnm] or {nvm-install-url}[NVM].

=== fnm

.~/.zprofile
[,zsh]
----
if command -v fnm >/dev/null 2>&1; then
  eval "$(fnm env --use-on-cd)"
fi
----

=== nvm

.~/.zshrc
[,zsh]
----
export NVM_DIR="${HOME}/.nvm"

[ -s "${NVM_DIR}/nvm.sh" ] && . "${NVM_DIR}/nvm.sh"
[ -s "${NVM_DIR}/bash_completion" ] && . "${NVM_DIR}/bash_completion"

if command -v nvm >/dev/null 2>&1; then
  autoload -U add-zsh-hook
  load-nvmrc() {
    local nvmrc_path="$(nvm_find_nvmrc)"
    if [ -n "${nvmrc_path}" ]; then
      local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")
      if [ "${nvmrc_node_version}" = "N/A" ]; then
        nvm install
      elif [ "${nvmrc_node_version}" != "$(nvm version)" ]; then
        nvm use
      fi
    elif [ -n "$(PWD=$OLDPWD nvm_find_nvmrc)" ] && [ "$(nvm version)" != "$(nvm version default)" ]; then
      echo 'Reverting to nvm default version'
      nvm use default
    fi
  }

  add-zsh-hook chpwd load-nvmrc
  load-nvmrc
fi
----

[#openssh]
== OpenSSH

=== Linux

[,console]
----
$ sudo apt-get install openssh-client
----

=== Mac

`openssh` is part of the standard macOS installation.

[#openssl]
== OpenSSL

=== Linux

[,console]
----
$ sudo apt-get install openssl
----

=== Mac

`openssl` is part of the standard macOS installation.

[#optipng]
== optipng

=== Linux

[,console]
----
$ sudo apt-get install optipng
----

=== Mac

[,console]
----
$ brew install optipng
----

[#oxipng]
== oxipng

=== Linux

Install {oxipng-install-url}[oxipng].

=== Mac

[,console]
----
$ brew install oxipng
----

[#pnpm]
== pnpm

Install {pnpm-install-url}[pnpm].

[#qpdf]
== qpdf

=== Linux

[,console]
----
$ sudo apt-get install qpdf
----

=== Mac

[,console]
----
$ brew install qpdf
----

[#shellcheck]
== ShellCheck

=== Linux

[,console]
----
$ sudo apt-get install shellcheck
----

=== Mac

[,console]
----
$ brew install shellcheck
----

[#shfmt]
== shfmt

=== Linux

[,console]
----
$ sudo apt-get install shfmt
----

=== Mac

[,console]
----
$ brew install shfmt
----

[#unzip]
== unzip

=== Linux

[,console]
----
$ sudo apt-get install unzip
----

=== Mac

`unzip` is part of the standard macOS installation.

== yamllint

=== Linux

[,console]
----
$ sudo apt-get install yamllint
----

=== Mac

[,console]
----
$ brew install yamllint
----

[#zstd]
== zstd

=== Linux

[,console]
----
$ sudo apt-get install zstd
----

=== Mac

[,console]
----
$ brew install zstd
----
