// SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
// SPDX-License-Identifier: Apache-2.0
= create_build_info_json
:script_url: https://github.com/sdavids/sdavids-shell-misc/blob/main/scripts/web/create_build_info_json.sh

{script_url}[This script^] will create a JSON file with the given name containing build information.

[NOTE]
====
The value of `build.id` is depending on where this script is run:

locally:: the current timestamp
AppVeyor:: the value of the `APPVEYOR_BUILD_ID` https://www.appveyor.com/docs/environment-variables/[environment variable]
Bitbucket:: the value of the `BITBUCKET_BUILD_NUMBER` https://support.atlassian.com/bitbucket-cloud/docs/variables-and-secrets/#Default-variables[environment variable]
CircleCI:: the value of the `CIRCLE_WORKFLOW_ID` https://circleci.com/docs/variables/#built-in-environment-variables[environment variable]
GitHub:: the value of the `GITHUB_RUN_ID` https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables[environment variable]
GitLab:: the value of the `CI_PIPELINE_ID` https://docs.gitlab.com/ee/ci/variables/predefined_variables.html[environment variable]
Jenkins:: the value of the `BUILD_ID` https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#using-environment-variables[environment variable]
TeamCity:: the value of the `BUILD_NUMBER` https://www.jetbrains.com/help/teamcity/predefined-build-parameters.html#1c215e8e[environment variable]
Travis:: the value of the `TRAVIS_BUILD_ID` https://docs.travis-ci.com/user/environment-variables/#default-environment-variables[environment variable]
====

[NOTE]
====
The value of `build.time` is either the value of the `SOURCE_DATE_EPOCH` https://reproducible-builds.org/specs/source-date-epoch/[environment variable] or the current timestamp.
====

== Usage

[,shell]
----
$ scripts/web/create_build_info_json.sh src/build-info.json
----

⇓

.src/build-info.json
[,json]
----
{"build":{"id":"1710116654","time":"2024-03-11T00:24:14Z"},"git":{"branch":"main","commit":{"id":"b530d501d059e1bbda58d96d78359014effa5584","time":"2024-03-11T00:22:45Z"}}}
----

== Related Scripts

* xref:scripts/web/create-build-info-js.adoc[]
* xref:scripts/web/create-build-info-ts.adoc[]
