// SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
// SPDX-License-Identifier: Apache-2.0
= create_build_info_json
:script_url: https://github.com/sdavids/sdavids-shell-misc/blob/main/scripts/web/create_build_info_json.sh

{script_url}[This script^] will create a JSON file at the given path containing build and source control information.

The given path can either be relative to the base directory (`-d`) or an absolute path—intermediate directories will not be created.

The following parameters are optional:

`d` :: the base directory (`$PWD` if not given)
`f` :: overwrite the existing file

[NOTE]
====
The value of `build.id` is depending on where this script is run:

locally:: the current timestamp
AppVeyor:: the value of the `APPVEYOR_BUILD_ID` https://www.appveyor.com/docs/environment-variables/[environment variable]
Bitbucket:: the value of the `BITBUCKET_BUILD_NUMBER` https://support.atlassian.com/bitbucket-cloud/docs/variables-and-secrets/#Default-variables[environment variable]
CircleCI:: the value of the `CIRCLE_WORKFLOW_ID` https://circleci.com/docs/variables/#built-in-environment-variables[environment variable]
GitHub:: the value of the `GITHUB_RUN_ID` https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables[environment variable]
GitLab:: the value of the `CI_PIPELINE_ID` https://docs.gitlab.com/ee/ci/variables/predefined_variables.html[environment variable]
Jenkins:: the value of the `BUILD_ID` https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#using-environment-variables[environment variable]
TeamCity:: the value of the `BUILD_NUMBER` https://www.jetbrains.com/help/teamcity/predefined-build-parameters.html#1c215e8e[environment variable]
Travis:: the value of the `TRAVIS_BUILD_ID` https://docs.travis-ci.com/user/environment-variables/#default-environment-variables[environment variable]
====

[NOTE]
====
The value of `build.time` is either the value of the `SOURCE_DATE_EPOCH` https://reproducible-builds.org/specs/source-date-epoch/[environment variable] or the current timestamp.

The following will give you the timestamp of the HEAD commit:

[,shell]
----
SOURCE_DATE_EPOCH="$(git log --max-count=1 --pretty=format:%ct)"
----
====

[NOTE]
====
This script will add source control information if the base directory (`-d`) is under Git version control, i.e., either the https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt---show-toplevel[top-level directory] or one its subdirectories.

[,console]
----
/tmp
├── git_repo
│   └── .git
│   └── src
└── other
----

-d /tmp:: source control information will not be added
-d /tmp/git_repo:: source control information will be added
-d /tmp/git_repo/src:: source control information will be added
-d /tmp/other:: source control information will not be added

The value of `git.commit.id` is the hash of the HEAD commit of the checked-out branch; the suffix `-next` will be appended if the working tree is dirty.
====

== Usage

[,console]
----
$ scripts/web/create_build_info_json.sh build-info.json

$ scripts/web/create_build_info_json.sh -f /tmp/build-info.json
$ scripts/web/create_build_info_json.sh -d ~/git_repo src/build-info.json
----

[,console]
----
$ scripts/web/create_build_info_json.sh src/build-info.json
----

⇓

.src/build-info.json
[,json]
----
{"build":{"id":"1710116654","time":"2024-03-11T00:24:14Z"},"git":{"branch":"main","commit":{"id":"b530d501d059e1bbda58d96d78359014effa5584","time":"2024-03-11T00:22:45Z"}}}
----

[,console]
----
$ SOURCE_DATE_EPOCH=0 scripts/web/create_build_info_json.sh src/build-info.json
----

⇓

.src/build-info.json
[,json]
----
{"build":{..."time":"1970-01-01T00:00:00Z"}...}
----

== Related Scripts

* xref:scripts/web/create-build-info-env.adoc[]
* xref:scripts/web/create-build-info-js.adoc[]
* xref:scripts/web/create-build-info-ts.adoc[]

== More Information

* https://reproducible-builds.org/specs/source-date-epoch[SOURCE_DATE_EPOCH]
* https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt---verify[git rev-parse --verify]
