// SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
// SPDX-License-Identifier: Apache-2.0
= macos_node_modules_fix
:script_url: https://github.com/sdavids/sdavids-shell-misc/blob/main/scripts/nodejs/macos_node_modules_fix.sh

{script_url}[This script^] will exclude all `node_modules` directories in the given directory (`$PWD` if not given) and its subdirectories from https://support.apple.com/en-us/104984[Time Machine] backups and prevent their https://support.apple.com/guide/mac-help/prevent-spotlight-searches-in-files-mchl1bb43b84/mac[Spotlight indexing].

[TIP]
====
Copy the script into your Node.js project and add it as a https://docs.npmjs.com/cli/v10/using-npm/scripts#life-cycle-scripts[preinstall life cycle script] to your `package.json` file:

.package.json
[,json]
----
{
...
  "scripts": {
    "preinstall": "scripts/macos_node_modules_fix.sh"
  }
}
----

For this to work, NPM https://docs.npmjs.com/cli/v10/using-npm/config#ignore-scripts[should not ignore pre- or post-scripts] (the default).

For https://cheatsheetseries.owasp.org/cheatsheets/NPM_Security_Cheat_Sheet.html#3-minimize-attack-surfaces-by-ignoring-run-scripts[security reasons] you might want to disable them globally via:

[,console]
----
$ npm config set ignore-scripts true
----

Use `--no-ignore-scripts` to enable the pre- or post-scripts for a specific NPM command:

[,console]
----
$ npm install --no-ignore-scripts
----

You can show your current configuration via:

[,console]
----
$ npm config ls -l
----

Alternatively, you can use this script as https://docs.npmjs.com/cli/v10/commands/npm-run-script[custom script] in your `package.json` file:

.package.json
[,json]
----
{
...
  "scripts": {
    "macos:fix-node-modules": "scripts/macos_node_modules_fix.sh"
  }
}
----

And execute it manually:

[,console]
----
$ npm install && node --run macos:fix-node-modules
----
====

== Usage

[,console]
----
$ scripts/nodejs/macos_node_modules_fix.sh
----

[,shell]
----
$ scripts/nodejs/macos_node_modules_fix.sh /tmp/example_project

$ xattr -r /tmp/example_workspace
$ tree --noreport -a /tmp/example_workspace
/tmp/example_workspace
├── project1
│   └── node_modules
└── project2
    └── node_modules
$ scripts/nodejs/macos_node_modules_fix.sh /tmp/example_workspace
$ xattr -r /tmp/example_workspace                                         <1>
/tmp/example_workspace/project1/node_modules: com.apple.metadata:com_apple_backup_excludeItem
/tmp/example_workspace/project2/node_modules: com.apple.metadata:com_apple_backup_excludeItem
$ tree --noreport -a /tmp/example_workspace
/tmp/example_workspace
├── project1
│   └── node_modules
│       └── .metadata_never_index                                         <2>
└── project2
    └── node_modules
        └── .metadata_never_index                                         <2>
----

<1> `node_modules` directories are not backed up by Time Machine

<2> Spotlight indexing prevented
