// SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
// SPDX-License-Identifier: Apache-2.0
= gradle_new_java_library
:function_url: https://github.com/sdavids/sdavids-shell-misc/blob/main/zfunc/gradle_new_java_library

{function_url}[This function^] will create a new Gradle https://docs.gradle.org/current/userguide/java_library_plugin.html[Java library] project with sensible, modern defaults and the given name.

The optional second parameter is the directory (`$PWD` if not given) the project is created in.

[NOTE]
====
A Git repository with `pre-commit` and `pre-push` https://git-scm.com/docs/githooks[hooks] will also be initialized for the project if `git` is installed.

This script uses https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work[Git commit signing] if `user.signingKey` is set in the https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key#telling-git-about-your-gpg-key[global Git configuration].
====

[TIP]
====
The generated default package will be `org.example`.

You can https://docs.gradle.org/8.6/release-notes.html#simpler-source-package-handling[change the default] by adding `org.gradle.buildinit.source.package` in https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties[Gradle properties]:

[,console]
----
$ printf 'org.gradle.buildinit.source.package=my.org' >>"${GRADLE_USER_HOME:=${HOME}}/gradle.properties"
----

If you want https://docs.gradle.org/8.7/release-notes.html#generating-concise-projects-with-gradle-init[no comments]  to be generated add `org.gradle.buildinit.comments=false` in https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties[Gradle properties]:

[,console]
----
$ printf 'org.gradle.buildinit.comments=false' >>"${GRADLE_USER_HOME:=${HOME}}/gradle.properties"
----
====

[TIP]
====
You might want to customize the defaults for the created `.editorconfig`, `.gitattributes`, `.gitignore`, `gradle.properties`, `pre-commit` or `pre-push`, e.g.:

.zfunc/gradle_new_java_library
[,shell]
----
    cat <<'EOF' >gradle.properties
...
EOF

    cat <<'EOF' >.gitignore
...
EOF

    cat <<'EOF' >.gitattributes
...
EOF

    cat <<'EOF' >.editorconfig
...
EOF

    cat <<'EOF' >.githooks/pre-commit
...
EOF

    cat <<'EOF' >.githooks/pre-push
...
EOF
----
====

[TIP]
====
You might want to use xref:functions/gh/repo-publish-to-gh.adoc[] to publish the newly created project to GitHub:

[,console]
----
$ gradle_new_java_library example-java-library
$ repo_publish_to_gh
✓ Created repository sdavids/example-java-library on GitHub
  https://github.com/sdavids/example-java-library
...
----
====

== Usage

[,console]
----
$ gradle_new_java_library example-java-library
$ gradle_new_java_library other-java-library /tmp
$ tree --noreport -a -I .git .
.
├── .editorconfig
├── .gitattributes
├── .githooks
│   ├── pre-commit
│   └── pre-push
├── .gitignore
├── gradle
│   ├── libs.versions.toml
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradle.properties
├── gradlew
├── gradlew.bat
├── lib
│   ├── build.gradle.kts
│   └── src
│       ├── main
│       │   ├── java
│       │   │   └── org
│       │   │       └── example
│       │   │           └── Library.java
│       │   └── resources
│       └── test
│           ├── java
│           │   └── org
│           │       └── example
│           │           └── LibraryTest.java
│           └── resources
└── settings.gradle.kts
$ git status
On branch main
nothing to commit, working tree clean
----

== Prerequisites

* xref:developer-guide::dev-environment/dev-installation.adoc#gradle[Gradle]

== Related Functions

* xref:functions/gh/repo-publish-to-gh.adoc[]

== More Information

* https://docs.gradle.org/current/userguide/build_init_plugin.html[Gradle - Build Init Plugin]
* https://docs.gradle.org/current/userguide/java_library_plugin.html[Gradle - Java library]
* https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties[Gradle properties]
* https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks[Git Hooks]
* https://git-scm.com/docs/gitattributes[gitattributes]
* https://git-scm.com/docs/gitignore[gitignore]
* https://editorconfig.org[EditorConfig]
