// SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
// SPDX-License-Identifier: Apache-2.0
= delete_ca_based_cert
:script_url: https://github.com/sdavids/sdavids-shell-misc/blob/main/scripts/cert/delete_ca_based_cert.sh

{script_url}[This script^] will delete a private key and a certificate from a certificate authority; the `key.pem` and `cert.pem` files will also be deleted.

The following parameters are optional:

`c` :: the common name (`localhost` if not given) of the certificate
`d` :: the directory (`$PWD` if not given) containing the key and certificate; the directory will be also deleted if empty and not `$PWD`

[NOTE]
====
Chrome, Docker, Firefox, and Safari need no further configuration.
====

[IMPORTANT]
====
Ensure that the xref:scripts/cert/create-ca.adoc[certificate authority has been created] and a xref:scripts/cert/create-ca-based-cert.adoc[private key and certificate have been created] before executing this script.
====

[IMPORTANT]
====
This script will not delete additional xref:scripts/cert/copy-ca-based-cert.adoc[copies], i.e., only the private key and certificate in the given directory (`-d`) and the CA will be removed.
====

[TIP]
====
Copy the script into your Node.js project and add it as a https://docs.npmjs.com/cli/v10/commands/npm-run-script[custom script] to your `package.json` file:

.package.json
[,json]
----
{
...
  "scripts": {
    "cert:delete": "scripts/delete_ca_based_cert.sh -d certs"
  }
}
----

[,console]
----
$ node --run cert:delete
----
====

== Usage

[,console]
----
$ scripts/cert/delete_ca_based_cert.sh
$ scripts/cert/delete_ca_based_cert.sh -d ~/.local/secrets/certs/localhost
$ scripts/cert/delete_ca_based_cert.sh -d ~/.local/secrets/certs/https.internal -c https.internal
----

== Prerequisites

* xref:developer-guide::dev-environment/dev-installation.adoc#easyrsa[EasyRSA]
* xref:developer-guide::dev-environment/dev-installation.adoc#openssl[OpenSSL]

== Related Scripts

* xref:scripts/cert/create-ca-based-cert.adoc[]
* xref:scripts/cert/copy-ca-based-cert.adoc[]
* xref:scripts/cert/renew-ca-based-cert.adoc[]
* xref:scripts/cert/create-ca.adoc[]
* xref:scripts/cert/delete-ca.adoc[]
