// SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
// SPDX-License-Identifier: Apache-2.0
= repo_new_local
:function_url: https://github.com/sdavids/sdavids-shell-misc/blob/main/zfunc/repo_new_local

{function_url}[This function^] will create a new local Git repository based on a https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository[GitHub template repository] with the given name.

[IMPORTANT]
====
This function needs the GitHub `delete_repo` permission.

[,console]
----
$ gh auth refresh -h github.com -s delete_repo
----
====

[IMPORTANT]
====
You should change the GitHub user and template being used:

.zfunc/repo_new_local
[,shell,highlight=2,4]
----
- readonly template='sdavids/sdavids-project-template'
+ readonly template='my-github-user/my-template'
- readonly gh_user_id='sdavids'
+ readonly gh_user_id='my-github-user'
----
====

[NOTE]
====
This script uses https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work[Git commit signing]; you need to:

* configure your https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key#telling-git-about-your-gpg-key[local git
config]
* https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account#adding-a-gpg-key[add your public GPG key] to GitHub

Alternatively, you can remove `--gpg-sign`:

.zfunc/repo_new_local
[,shell,highlight=3]
----
  git commit \
    --quiet \
-   --gpg-sign \
    --signoff \
----
====

[NOTE]
====
Sometimes GitHub is slow or you have bad latency.
In that case you need to increase the time used to wait between GitHub interactions:

.zfunc/repo_new_local
[,shell]
----
wait_for_github=10
----
====

== Usage

[,console]
----
$ repo_new_local my-new-local-repo
----

== Prerequisites

* xref:developer-guide::dev-environment/dev-installation.adoc#gh-cli[GitHub CLI]

== Related Functions

* xref:functions/gh/repo-publish-to-gh.adoc[]
* xref:functions/gh/repo-new-gh.adoc[]

== More Information

* https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository[GitHub template repository]
